apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - api-configmap.yaml
  - postgres-init-configmap.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - postgres-networkpolicy.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-ingress.yaml
  - api-hpa.yaml
